services:
  cherkasyoblenergo-db:
    container_name: cherkasyoblenergo-db
    image: postgres:17-alpine
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "${DB_EXTERNAL_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - cherkasyoblenergo-network

volumes:
  postgresql_data:
    name: postgresql_data

networks:
  cherkasyoblenergo-network:
    name: cherkasyoblenergo-network
    driver: bridge
