name: Gitleaks

on: [push, pull_request]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run gitleaks scan
        uses: zricethezav/gitleaks-action@v1
        with:
          args: "--source ."
